### PR TITLE
Make dueljs UMD compatible

### PR DESCRIPTION
**Pull request by RasCarlito**
Hi!

Simply modified dueljs to make it requirable using AMD/CommonJS environments aswell as a browser global variable.

Example using require.js:
```javascript
// Some module
define(['duel'], function (duel) {
  var channel = duel.channel('awesome-tab-channel');

  channel.on('message', function () {
    // Do something fantastic!
  });
});
```

I tested it manually using require.js in my clients project and using your demo file ```public/index.html```.
But I was unable to make the unit tests run, I got a parse error when running them =(

Another possible issue is that when require.js is loaded in the page but you try to load the script globally using a ```<script>``` tag in the html, the ```duel``` variable won't exist in the ```window``` object. This could become confusing.
It could be solved simply by doing
```javascript
var duel = window.duel = {};
```
at the beginning of the script (line 30).
But, polluting the global environment when the developper actually wants to load the library via require is not so great. What do you think ?

Another thing, I don't know what kind of packaging you used to minify the script, so I didn't modify the ```duel.min.js``` file. Just tell me what to use and I'll be glad to add it to the request. =)

Thanks for this cool library!
Cheers

### CODE REVIEW

**Comment by studentIvan** [comment]
Thank you man, i minify this file manually before)

**Comment by RasCarlito** [comment]
@NeXTs I don't see why it wouldn't work with webpack.

I haven't tested it with webpack but I have other libs where I have the exact same UMD definition and those lib work fine with webpack.

How do you import the lib in your code ?

**Comment by NeXTs** [comment]
as usual :D 
`import duel from 'dueljs'`

saying it doesn't work I mean [this](https://github.com/studentIvan/dueljs/issues/13)

**Comment by RasCarlito** [comment]
That is wierd. You say putting `window` instead of `this` as the global reference fixes your issue ?

Again, I have another lib where I use the same UMD definition with `this` as the global reference and no problem there.

But putting `this` as the global reference is only useful if the lib is going to run in the browser and on the server. This lib is only for browser runtimes as far as I know.

You should make a PR with the fix :)

**Comment by NeXTs** [comment]
I know that it's weird :\

**Pull request merged**
